[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=3
loglevel=info
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log

[program:temporal-server]
command=temporal server start-dev --ip 0.0.0.0 --port 7233 --ui-port 8233 --ui-public-path /temporal
autorestart=true
stdout_logfile=/var/log/temporal-server.log
stderr_logfile=/var/log/temporal-server.err

[program:fastapi]
command=uv run uvicorn main:app --host 0.0.0.0 --port 8000
autorestart=true
stdout_logfile=/var/log/fastapi.log
stderr_logfile=/var/log/fastapi.err

[program:temporal-worker]
command=uv run -m temporal.worker
autorestart=true
stdout_logfile=/var/log/temporal-worker.log
stderr_logfile=/var/log/temporal-worker.err
